name: sync
on:
    schedule:
        - cron: "0 0 * * *"
    workflow_dispatch:
env:
    REPO: ${{ github.repository }}
    LIBS: ${{ vars.LIBS }}
    TOKEN: ${{ secrets.TOKEN }}
jobs:
    sync:
        runs-on: ubuntu-latest
        steps:
            - name: clone
              run: |
                  git clone https://github.com/cdnjs/cdnjs.git --depth=1 --filter=blob:none --no-checkout
                  git clone https://$TOKEN@github.com/$REPO.git $REPO --depth=1 --filter=blob:none --no-checkout
            - name: checkout
              run: |
                  cd cdnjs
                  git sparse-checkout init --cone
                  for i in $LIBS
                  do
                  git sparse-checkout add ajax/libs/$i
                  done
                  git checkout
                  cd ..
                  cd $REPO
                  git sparse-checkout init --cone
                  git sparse-checkout set libs
                  git checkout
            - name: sync
              run: |
                  rm -rf $REPO/libs
                  for i in $LIBS
                  do
                  mkdir -p $REPO/libs/$i
                  cp -r cdnjs/ajax/libs/$i/* $REPO/libs/$i
                  done
            - name: commit
              run: |
                  cd $REPO
                  git config user.name github-actions[bot]
                  git config user.email github-actions[bot]@users.noreply.github.com
                  git add .
                  git commit --allow-empty -m "sync"
            - name: push
              run: |
                  cd $REPO
                  git push https://$TOKEN@github.com/$REPO.git
