name: sync
on:
    schedule:
        - cron: "0 0 * * *"
    workflow_dispatch:
jobs:
    sync:
        runs-on: ubuntu-latest
        steps:
            - name: clone
              run: |
                  git clone https://github.com/cdnjs/cdnjs.git --depth=1 --filter=blob:none --no-checkout
                  git clone https://${{ secrets.TOKEN }}@github.com/${{ github.repository }}.git static --depth=1 --filter=blob:none --no-checkout
            - name: checkout
              run: |
                  cd cdnjs
                  git sparse-checkout init --cone
                  for i in ${{ vars.LIBS }}
                  do
                  git sparse-checkout add ajax/libs/$i
                  done
                  git checkout
                  cd ../static
                  git sparse-checkout init --cone
                  git sparse-checkout set libs
                  git checkout
            - name: sync
              run: |
                  rm -rf static/libs
                  cp -r cdnjs/ajax/libs static/libs
            - name: commit
              run: |
                  cd static
                  git config --global user.name github-actions[bot]
                  git config --global user.email github-actions[bot]@users.noreply.github.com
                  git add .
                  git commit --allow-empty -m "chore: sync libs"
            - name: push
              run: |
                  cd static
                  git push https://${{ secrets.TOKEN }}@github.com/${{ github.repository }}.git
